version: "3.9"
services:
  auth:
    restart: always
    environment:
      - DB_HOST=postgres
    env_file:
      - ${ENV}.env
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./postgres-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: