apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-auth-postgres-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app: go-auth-postgres